### ISSUE TITLE
Research how trello makes their cards automatically center/fit on the screen in mobile

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/Checklists#124]

**Comment by rrickgauer** [comment]
https://css-tricks.com/almanac/properties/s/scroll-snap-align/

**Comment by rrickgauer** [comment]
```css
.card-checklist {
    scroll-snap-align: center;
}
```
